FROM python:3.12-slim-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    supervisor \
    ffmpeg \
    nodejs \
    npm \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
RUN mkdir -p /app/ffmpeg/bin \
    && ln -s /usr/bin/ffmpeg /app/ffmpeg/bin/ffmpeg \
    && ln -s /usr/bin/ffprobe /app/ffmpeg/bin/ffprobe
